repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-xml
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        types: [python]
        language: system
