################################################################################
# Environment script generated by ilcsoft-install on Fri Dec  1 16:50:03 2023
# for lcgeo located at [ /opt/ilcsoft/v02-02-03-pixel/lcgeo/v00-16-07 ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export ILCSOFT_CMAKE="/opt/ilcsoft/v02-02-03-pixel/ILCSoft.cmake"
export ILCSOFT_CMAKE_ENV="/opt/ilcsoft/v02-02-03-pixel/ILCSoft.cmake.env.sh"
export MAKEOPTS="-j4"
export CXX="g++"
export CC="gcc"


#--------------------------------------------------------------------------------
#     lcgeo
#--------------------------------------------------------------------------------
export lcgeo_DIR="/opt/ilcsoft/v02-02-03-pixel/lcgeo/v00-16-07"
export lcgeo_ENVINIT="${lcgeo_DIR}/bin/thislcgeo.sh"
# --- additional lcgeo commands ------- 
test -r ${lcgeo_ENVINIT} && . ${lcgeo_ENVINIT}


#--------------------------------------------------------------------------------
#     DD4hep
#--------------------------------------------------------------------------------
export DD4HEP="/opt/ilcsoft/v02-02-03-pixel/DD4hep/v01-11-02"
export DD4HEP_ENVINIT="${DD4HEP}/bin/thisdd4hep.sh"
# --- additional DD4hep commands ------- 
test -r ${DD4HEP_ENVINIT} && . ${DD4HEP_ENVINIT}
# --- additional ROOT commands ------- 
test -r /opt/ilcsoft/v02-02-03-pixel/root/6.18.04/bin/thisroot.sh && . /opt/ilcsoft/v02-02-03-pixel/root/6.18.04/bin/thisroot.sh


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/opt/ilcsoft/v02-02-03-pixel/lcio/v02-17"
# --- additional LCIO commands ------- 
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LCIO/lib64:$LD_LIBRARY_PATH"
export PYTHONPATH="$LCIO/python:$LCIO/python/examples:$PYTHONPATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/opt/ilcsoft/v02-02-03-pixel/gear/v01-09"
# --- additional GEAR commands ------- 
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/opt/ilcsoft/v02-02-03-pixel/CLHEP/2.3.4.3"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
# --- additional CLHEP commands ------- 
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     Geant4
#--------------------------------------------------------------------------------
export G4INSTALL="/opt/ilcsoft/v02-02-03-pixel/geant4/10.04.p03"
export G4SYSTEM="unknown-g++"
export G4ENV_INIT="$G4INSTALL/bin/geant4.sh"
# --- additional Geant4 commands ------- 
test -r ${G4ENV_INIT} && { cd $(dirname ${G4ENV_INIT}) ; . ./$(basename ${G4ENV_INIT}) ; cd $OLDPWD ; }


#--------------------------------------------------------------------------------
#     Qt5
#--------------------------------------------------------------------------------
export QTDIR="/opt/ilcsoft/v02-02-03-pixel/Qt5/v5.13.1"
# --- additional Qt5 commands ------- 
export PATH="$QTDIR/bin:$PATH"
export LD_LIBRARY_PATH="$QTDIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     XercesC
#--------------------------------------------------------------------------------
export XercesC_HOME="/opt/ilcsoft/v02-02-03-pixel/xercesc/v3.2.2"
# --- additional XercesC commands ------- 
export PATH="$XercesC_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$XercesC_HOME/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     Boost
#--------------------------------------------------------------------------------
export BOOST_ROOT="/opt/ilcsoft/v02-02-03-pixel/boost/1.71.0"
# --- additional Boost commands ------- 


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
# --- additional CMake commands ------- 
export PATH="/opt/ilcsoft/CMake/3.15.5/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/opt/ilcsoft/v02-02-03-pixel/ilcutil/v01-06-02"
# --- additional ILCUTIL commands ------- 
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
test -r ${lcgeo_ENVINIT} && . ${lcgeo_ENVINIT}
