name: downstream-build

on:
  pull_request:
  workflow_dispatch:

jobs:
  downstream-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: key4hep/key4hep-actions/downstream-build@main
