name: Key4hep build

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
  schedule:
        - cron: '17 5 * * *'


jobs:
  build:
    strategy:
      matrix:
        build_type: ["release", "nightly"]
        image: ["alma9", "ubuntu22", "centos7"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: key4hep/key4hep-actions/key4hep-build@main
      with:
        build_type: ${{ matrix.build_type }}
        image: ${{ matrix.image }}
