name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: cvmfs-contrib/github-action-cvmfs@10197e000cc0add8e54ac4fb73d3ed44e2de72b4 # v5.5
    - uses: aidasoft/run-lcg-view@b4da52e1c5ccb70a60ad4e7216de0a90664d5849 # v6.0.2
      with:
        container: el9
        view-path: /cvmfs/sw-nightlies.hsf.org/key4hep
        run: |
          python -m venv /root/pre-commit-venv
          source /root/pre-commit-venv/bin/activate
          pip install pre-commit
          export PYTHONPATH=$VIRTUAL_ENV/lib/python3.$(python3 -c 'import sys; print(f"{sys.version_info[1]}")')/site-packages:$PYTHONPATH
          # Newer versions of git are more cautious around the github runner
          # environment and without this git rev-parse --show-cdup in pre-commit
          # fails
          git config --global --add safe.directory $(pwd)
          pre-commit run --show-diff-on-failure \
            --color=always \
            --all-files
